# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pyinjective.proto.exchange import injective_tc_derivatives_rpc_pb2 as exchange_dot_injective__tc__derivatives__rpc__pb2


class InjectiveTCDerivativesRPCStub(object):
    """InjectiveTCDerivativesRPC defines gRPC API of the TC Derivatives API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrdersHistory = channel.unary_unary(
                '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/OrdersHistory',
                request_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersHistoryRequest.SerializeToString,
                response_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersHistoryResponse.FromString,
                _registered_method=True)
        self.StreamOrdersHistory = channel.unary_stream(
                '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/StreamOrdersHistory',
                request_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersHistoryRequest.SerializeToString,
                response_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersHistoryResponse.FromString,
                _registered_method=True)
        self.Orders = channel.unary_unary(
                '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/Orders',
                request_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersRequest.SerializeToString,
                response_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersResponse.FromString,
                _registered_method=True)
        self.StreamOrders = channel.unary_stream(
                '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/StreamOrders',
                request_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersRequest.SerializeToString,
                response_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersResponse.FromString,
                _registered_method=True)
        self.Trades = channel.unary_unary(
                '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/Trades',
                request_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.TradesRequest.SerializeToString,
                response_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.TradesResponse.FromString,
                _registered_method=True)
        self.StreamTrades = channel.unary_stream(
                '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/StreamTrades',
                request_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamTradesRequest.SerializeToString,
                response_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamTradesResponse.FromString,
                _registered_method=True)
        self.Positions = channel.unary_unary(
                '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/Positions',
                request_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.PositionsRequest.SerializeToString,
                response_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.StreamPositions = channel.unary_stream(
                '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/StreamPositions',
                request_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamPositionsRequest.SerializeToString,
                response_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamPositionsResponse.FromString,
                _registered_method=True)


class InjectiveTCDerivativesRPCServicer(object):
    """InjectiveTCDerivativesRPC defines gRPC API of the TC Derivatives API.
    """

    def OrdersHistory(self, request, context):
        """Get TC order history combining settlement requests with on-chain order data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOrdersHistory(self, request, context):
        """Stream updates to TC order history entries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Orders(self, request, context):
        """Get TC derivative limit orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOrders(self, request, context):
        """Stream updates to TC derivative limit orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trades(self, request, context):
        """Get TC derivative trades
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrades(self, request, context):
        """Stream newly executed trades from TC Derivative Markets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Positions(self, request, context):
        """Positions gets the positions for a trader. V2 removed some redundant fields
        and had performance improvements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPositions(self, request, context):
        """StreamPositions streams TC derivatives position updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InjectiveTCDerivativesRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrdersHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.OrdersHistory,
                    request_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersHistoryRequest.FromString,
                    response_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersHistoryResponse.SerializeToString,
            ),
            'StreamOrdersHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOrdersHistory,
                    request_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersHistoryRequest.FromString,
                    response_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersHistoryResponse.SerializeToString,
            ),
            'Orders': grpc.unary_unary_rpc_method_handler(
                    servicer.Orders,
                    request_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersRequest.FromString,
                    response_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersResponse.SerializeToString,
            ),
            'StreamOrders': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOrders,
                    request_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersRequest.FromString,
                    response_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersResponse.SerializeToString,
            ),
            'Trades': grpc.unary_unary_rpc_method_handler(
                    servicer.Trades,
                    request_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.TradesRequest.FromString,
                    response_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.TradesResponse.SerializeToString,
            ),
            'StreamTrades': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrades,
                    request_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamTradesRequest.FromString,
                    response_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamTradesResponse.SerializeToString,
            ),
            'Positions': grpc.unary_unary_rpc_method_handler(
                    servicer.Positions,
                    request_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.PositionsRequest.FromString,
                    response_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.PositionsResponse.SerializeToString,
            ),
            'StreamPositions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPositions,
                    request_deserializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamPositionsRequest.FromString,
                    response_serializer=exchange_dot_injective__tc__derivatives__rpc__pb2.StreamPositionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InjectiveTCDerivativesRPC(object):
    """InjectiveTCDerivativesRPC defines gRPC API of the TC Derivatives API.
    """

    @staticmethod
    def OrdersHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/OrdersHistory',
            exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersHistoryRequest.SerializeToString,
            exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOrdersHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/StreamOrdersHistory',
            exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersHistoryRequest.SerializeToString,
            exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Orders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/Orders',
            exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersRequest.SerializeToString,
            exchange_dot_injective__tc__derivatives__rpc__pb2.OrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/StreamOrders',
            exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersRequest.SerializeToString,
            exchange_dot_injective__tc__derivatives__rpc__pb2.StreamOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Trades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/Trades',
            exchange_dot_injective__tc__derivatives__rpc__pb2.TradesRequest.SerializeToString,
            exchange_dot_injective__tc__derivatives__rpc__pb2.TradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/StreamTrades',
            exchange_dot_injective__tc__derivatives__rpc__pb2.StreamTradesRequest.SerializeToString,
            exchange_dot_injective__tc__derivatives__rpc__pb2.StreamTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Positions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/Positions',
            exchange_dot_injective__tc__derivatives__rpc__pb2.PositionsRequest.SerializeToString,
            exchange_dot_injective__tc__derivatives__rpc__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/injective_tc_derivatives_rpc.InjectiveTCDerivativesRPC/StreamPositions',
            exchange_dot_injective__tc__derivatives__rpc__pb2.StreamPositionsRequest.SerializeToString,
            exchange_dot_injective__tc__derivatives__rpc__pb2.StreamPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
